name: format

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "ci"
    paths:
      - "lua/**"

jobs:
  stylua-check:
    name: "Formatting check with Stylua"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          version: 2.3.1
          args: --check .
